name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4a58a4d88d06553b5650984d602c9f7e2ef4dae1547e5aa2d5f959059ae210c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
